### ISSUE TITLE
retry artifact upload

### ISSUE THREAD

**Issue by zhangyoufu** [zhangyoufu/macOS#2]
```
[ERROR] Release aborted
Traceback (most recent call last):
  File ".github/release.py", line 283, in main
AssertionError: 500 Internal Server Error
{"message":"Error saving asset","request_id":"0400:756A:D7C48:10EE1E:5E4D7EAE"}
Traceback (most recent call last):
  File ".github/release.py", line 283, in main
    assert rsp.status_code == 201, f'{rsp.status_code} {rsp.reason}\n{rsp.text}'
AssertionError: 500 Internal Server Error
{"message":"Error saving asset","request_id":"0400:756A:D7C48:10EE1E:5E4D7EAE"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".github/release.py", line 321, in <module>
    main()
  File ".github/release.py", line 307, in main
    assert rsp.status_code != 204
AssertionError
##[error]Process completed with exit code 1.
```

**Comment by zhangyoufu** [comment]
```
Traceback (most recent call last):
  File ".github/release.py", line 291, in main
    assert rsp.status_code == 201, f'{rsp.status_code} {rsp.reason}\n{rsp.text}'
AssertionError: 400 Bad Request
{"message":"Bad Content-Length: ","request_id":"0403:1F84:E2B9:12CB5:5E5EFD5E"}
```

**Comment by zhangyoufu** [comment]
done
